[gcp_service_account]
type = "service_account"
project_id = "sonorous-veld-460813-s7"
private_key_id = "1372317a84f69ed17e909b150cfb495053a83747"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4vOqE8g/LHaeH
qYPoFTQphiaonQs6hUIpWtsXvOJA8RaqeYOAEewK4xhmxuB2FgG8n6fALZYj3jx1
QSJQ5lGmCBCS78XmuXgJNaBSRHATqDAnw1sNu7ytiWgbXSbOF4mrLU843+46U+1i
NCDdKeqO/X20HI4yzuLiFtaEfzudfaq8CQZuOBlrnFvNiaX94iQpkQH/IonKbs+1
3zuMCYBys3LI38p9Ja1vZbuhl+Dr41/JWzpQKxuwyXSQJRaZ8GHVOoCemXgeXi0U
naVpr8L1iyi64ltRd0bz/dFgKwkXLKkKD7dNBEpv+MOqyuVzB8uSyX3LSCs9SLVm
EBQbQxb7AgMBAAECggEAD94CEqsr2hlQ82EG+F8h3NMt7NuYRE1/0keAe/h4QnWy
qa/IMK7ZZFH/HYzFaL8ZJRdddC82Lxx+et++T86Igsc8jTJVAC079yaI/6frLHUM
tc2cu4A9g3ZC397PX3I8G9zHai4pqw7cW8v4aqaYA/IX4ul0+T411I97m2PGPg+Q
vtyswmI+Ssu7E2Pu7v6bNityWxzq/00e/t+xczfFS9TcAQVWS8mEXdwcjskBO0BV
nKQwRVTVhvADAHm4toKVfqToB1RanByW40Tze75H98CAZzgJX0ni4qOFAcBp8P4e
VLfxQKoWVngJWGL8hwxF+4+LkFhOsKvbTYkfISkvaQKBgQDjNQgQ5huxVSQ+oIVf
7HsiMINEfP4o9H4YgLOhkCM3itQfJpasYMOjDKHVadVZLVj4LhG2aNfF9MdvJPGx
4PUzz/3o2WtE+aKl6MkhmoznmglTS9ffKSbQoVg+nQ4829l3+QOVk49yrIAI7PZB
lHkXP/7VAR3Ry9+SjgHeDrrfhwKBgQDQJh1mizQR/qMkibO3UDq/W02o1ebLhNik
1aIyBggBtD80E71Y0XzpWeAIGqxhnxbNzGnPJbe2hguqWRzfdZFxABRQRFJbsHrP
zqbGRHtqy8Xc560XFr9sKD39H+pgM3/5Od/5ITk4Vc4lpJMnkwa4smjULnO0fhML
xLUtzfBh7QKBgCu/i1UNqalkln0ElYnZ0//KTYxDcQDbyufW6D+krFNGhP+Wg46f
dywPA54/KZhpNedbn4d6+okgT8Jj37H7edtHIkHSk2gNlTbS8t9ojdcOftsuEFvk
5ZdoacBsp1AqmN4T8Y+8gPN4qZKOZgBMoWBLrzq+Y0qBMgRbGZrzRSJDAoGBAMHH
yjVOQVLDYnTAsgxmZ9sAkIMvaGdurRaAQTka/lc/zFuaSPwoQ4cngfdphbR4nI1J
0fPk5GzLzI5x2fx7gsTV0xOLF7V+zkcq137cAJ5DSVjIYw+MwPdbW6KNFPEs4OZQ
qCBSeufkkj/fQJRmP6qxhgCLonKVsPuSzS3wfOtdAoGAHNEdS4kQtc6EWJlGJwiz
Buju5aL0tfHJSAeOTQnGU86Jsik4AHSZTAZdEwAwAtQowLNy3EBYGs4K3REapkOL
4UKF4ogAlfyOt6u9FvZGgjQ0guv37iO5org/+pPvewii6mYt2C/XCyqZWdwzrcOf
DVh/PBUgo24yHwUv7JGCh3Q=
-----END PRIVATE KEY-----"""
client_email = "tds-bot@sonorous-veld-460813-s7.iam.gserviceaccount.com"
client_id = "102034093549530248457"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tds-bot%40sonorous-veld-460813-s7.iam.gserviceaccount.com"
